### PR TITLE
Fix skus-for-multiple-types typos

### PR DESCRIPTION
**Pull request by pilor**

### CODE REVIEW

**Comment by DCtheGeek** [comment]
Once this is merged, I can signoff on PR MicrosoftDocs/azure-docs#7901 to docs as the files need to be updated here first.

**Comment by pilor** [comment]
@DCtheGeek merge complete

**Comment by BryanLa** [comment]
Hi @pilor, @DCtheGeek - looks like the deletion of azurepolicyset.json  in this PR is causing my build to fail on files in the azure-docs-pr repo. For instance, the [
Allowed SKUs for storage accounts and virtual machines](https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/azure-policy/scripts/allowed-skus-storage.md) article was using it via a CRR/include:

`[!code-json[main](../../../policy-templates/samples/PolicyInitiatives/skus-for-mutiple-types/azurepolicyset.json "Allowed SKUs for Storage Accounts and Virtual Machines")]`

Adding @tysonn for awareness, in case others are seeing this.

**Comment by DCtheGeek** [comment]
Hi @BryanLa.  We are aware and have already communicated with @tysonn.  The related update just got merged in (MicrosoftDocs/azure-docs#7901) so hopefully this is resolved soon.

**Comment by BryanLa** [comment]
Excellent, thanks @DCtheGeek.

**Pull request merged**
