### PR TITLE
API Connection Blacklist Policy

### PR DESCRIPTION
**Pull request by kskvarci**

### CODE REVIEW

**Comment by pilor** [comment]
Can you supply an example JSON body of a Microsoft.web/connections resource that this is intended to deny?

**Comment by mentat9** [comment]
Shouldn't we not be using the term Blacklist (or Whitelist)?

**Comment by kskvarci** [comment]
Here's an example resource body that the policy might evaluate:

{
	"type": "Microsoft.Web/connections",
	"apiVersion": "2016-06-01",
	"name": "gmail",
	"location": "eastus2",
	"properties": {
		"displayName": "gmail connection",
		"customParameterValues": {},
		"api": {
			"id": "[concat('/subscriptions/[subid]/providers/Microsoft.Web/locations/eastus2/managedApis/gmail"
		}
	}
}

**Comment by pilor** [comment]
Like mentat9 commented on earlier.  If you want to merge this please remove the term "blacklist".  

I'm also not convinced that "name" is what you want to be looking at.  The name of a resource is typically arbitrary.  Based on the example you gave the api.id property is what truly defines what API is being used.  Is there really a restriction that a connection to gmail is named "gmail", not just referencing the "gmail" API in api.id?

**Comment by kenieva** [comment]
All sample policy definitions pull requests should go to our community repo: https://github.com/Azure/CommunityPolicyRepo. Thank you!

**Pull request closed without merging**
