### PR TITLE
blinQ: Fix issue with wrong compliance state for blob storage with no table services.

### PR DESCRIPTION
**Pull request by heintonny**
The policy identify wrong policy state for blob storages with no table services.

We suggest this update to the policyRule to require at least 1 instance of tables.

### CODE REVIEW

**Comment by heintonny** [comment]
The sugested solution will require a new alias tables

**Comment by heintonny** [comment]
Update commit. Changed to validate if 

          {
            "field": "Microsoft.Storage/storageAccounts/tableServices/tables/tableName",
            "exists": true
          }

.... this seems to work. Simple blob storage accounts no longer get wrong compliance state, need to test if the policy still evaluate table storage correctly.

**Comment by robga** [comment]
Changes can not be made to built-in policies directly in this repo. If you find an issue in a built-in policy, feel free to open an issue, or open a Microsoft Azure support ticket. Changes to built-ins are made out-of-band and will be represented in this repo after the next built-in policy release.
https://github.com/Azure/azure-policy/tree/master/built-in-policies#contributing

I have notified the team who owns this built-in policy for the issue. They will triage it.

**Comment by johnmic** [comment]
Storage Resource API team has looked into this, and it looks like there is an inconsistency in the LIST tableService and GET tableService APIs which is causing the issue. We plan to address it there and make it so a workaround like this should not be necessary.

**Pull request closed without merging**
