### PR TITLE
Fix mode casing

### PR DESCRIPTION
**Pull request by pilor**

### CODE REVIEW

**Comment by nasarbasha** [comment]
Hello,
 Is this policy working? I deployed it in one of a subscription and did create an assignment via portal but due to some reason it is not white listing the policy def id i gave. I gave the policy def id of a built in role reader.
Thanks

**Comment by pilor** [comment]
@nasarbasha Which policy are you referring to?  This PR made a small modification to a bunch of different policies.

**Comment by nasarbasha** [comment]
Hello Chris,

It is the whitelisting of allowed Iam role definitions.
Due to some reason I am not able to whitelist a reader role which is a built in role.

Thanks,
Nasar

**Comment by pilor** [comment]
Built in roles can be referenced either by their tenant-level ID (/providers/microsoft.authorization/roleDefinitions/{guid}) or as a subscription level ID (/subscriptions/{subId}/providers/microsoft.authorization/roleDefinitions/{guid}) depending on the scenario unfortunately.  If you add both of those options for each built-in role you want to whitelist you should see the correct results.

**Pull request merged**
