### PR TITLE
changed and added policies to audit cmk ussage

### PR DESCRIPTION
**Pull request by Netkracker**

### CODE REVIEW

**Comment by Netkracker** [comment]
@microsoft-github-policy-service agree [company="{Swiss Post}"]

**Comment by Netkracker** [comment]
@microsoft-github-policy-service agree company="Swiss Post"

**Comment by Netkracker** [comment]
@microsoft-github-policy-service agree company=Swiss Post

**Comment by robga** [comment]
https://github.com/Azure/azure-policy/tree/master/built-in-policies#contributing

**Comment by Netkracker** [comment]
hi @robga thank you for the information, and I apologize for any inconvenience. Since the mentioned docs do not provide an official method to allow even effect changes for built-in policies, we at Swiss Post will fork them and create our own.

**Pull request closed without merging**
